package docker

import (
	"github.com/mensylisir/kubexm/pkg/step"
	commonstep "github.com/mensylisir/kubexm/pkg/step/common"
)

// NewManageCriDockerdServiceStep creates a new step to manage the "cri-dockerd" service
// by returning an instance of the common ManageServiceStep configured for cri-dockerd.
// - instanceName: A specific name for this step instance.
//                 If empty, a default name will be generated by the common step.
// - action: The service action to perform (e.g., commonstep.ActionStart, commonstep.ActionEnable).
// - sudo: Whether the systemctl command should be run with sudo (typically true).
func NewManageCriDockerdServiceStep(instanceName string, action commonstep.ServiceAction, sudo bool) step.Step {
	// The service name for cri-dockerd might sometimes be "cri-docker.service" or "cri-dockerd.service"
	// For consistency, let's use "cri-dockerd". Tasks should ensure the actual service file matches.
	return commonstep.NewManageServiceStep(instanceName, action, "cri-dockerd", sudo)
}
