package docker

import (
	"github.com/mensylisir/kubexm/pkg/step"
	commonstep "github.com/mensylisir/kubexm/pkg/step/common"
)

// NewManageDockerServiceStep creates a new step to manage the "docker" service
// by returning an instance of the common ManageServiceStep configured for docker.
// - instanceName: A specific name for this step instance.
//                 If empty, a default name will be generated by the common step.
// - action: The service action to perform (e.g., commonstep.ActionStart, commonstep.ActionEnable).
// - sudo: Whether the systemctl command should be run with sudo (typically true).
func NewManageDockerServiceStep(instanceName string, action commonstep.ServiceAction, sudo bool) step.Step {
	return commonstep.NewManageServiceStep(instanceName, action, "docker", sudo)
}
