package common

// This file defines standardized keys for use with the caching mechanisms in pkg/cache.
// Using constants for cache keys helps prevent typos and ensures consistency across the codebase
// when different parts of the system need to access the same cached data.

const (
	// --- Pipeline Cache Keys ---
	// These keys are typically used for data shared across the entire pipeline execution.

	// CacheKeyControlPlaneEndpoint stores the calculated control plane endpoint (e.g., "vip:6443" or "master1_ip:6443").
	CacheKeyControlPlaneEndpoint = "kubexm.pipeline.controlplane.endpoint"

	// CacheKeyKubeadmJoinCommandMaster stores the full 'kubeadm join' command for joining master nodes.
	CacheKeyKubeadmJoinCommandMaster = "kubexm.pipeline.kubeadm.join.master"
	// CacheKeyKubeadmJoinCommandWorker stores the full 'kubeadm join' command for joining worker nodes.
	CacheKeyKubeadmJoinCommandWorker = "kubexm.pipeline.kubeadm.join.worker"

	// CacheKeyKubeadmBootstrapToken stores the bootstrap token generated by 'kubeadm init'.
	CacheKeyKubeadmBootstrapToken = "kubexm.pipeline.kubeadm.bootstraptoken"
	// CacheKeyKubeadmCACertHashes stores the CA certificate hashes for discovery.
	CacheKeyKubeadmCACertHashes = "kubexm.pipeline.kubeadm.discovery.cacertsha256"
	// CacheKeyKubeadmCertificateKey stores the certificate key for uploading control-plane certificates.
	CacheKeyKubeadmCertificateKey = "kubexm.pipeline.kubeadm.certificatekey"

	// CacheKeyClusterCACert stores the cluster's main CA certificate content (PEM encoded).
	CacheKeyClusterCACert = "kubexm.pipeline.pki.ca.cert"
	// CacheKeyClusterCAKey stores the cluster's main CA private key content (PEM encoded) - use with extreme caution.
	// Typically only needed by the Generate*CertSteps on the control node.
	CacheKeyClusterCAKey = "kubexm.pipeline.pki.ca.key"

	// CacheKeyAdminKubeconfig stores the content of the admin.conf file after cluster creation.
	CacheKeyAdminKubeconfig = "kubexm.pipeline.kubeconfig.admin"

	// --- Module Cache Keys ---
	// Example: CacheKeyModuleEtcdEndpoints stores calculated etcd endpoints within an Etcd module.
	// CacheKeyModuleEtcdEndpoints = "kubexm.module.etcd.endpoints"

	// --- Task Cache Keys ---
	// Example: CacheKeyTaskDownloadedFilePath stores the path to a file downloaded by a specific task.
	// Such keys might be more dynamic, e.g., fmt.Sprintf("kubexm.task.%s.filepath.%s", taskName, fileName)
	// For now, specific examples are omitted as they are highly task-dependent.

	// --- Step Cache Keys ---
	// Step-specific cache is often for internal step state, e.g. CurrentStepSpec.
	// General purpose keys for steps are less common across different steps.
)
