package common

const (
	CacheKeyControlPlaneEndpoint     = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].controlplane.endpoint"
	CacheKeyKubeadmJoinCommandMaster = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.join.master"
	CacheKeyKubeadmJoinCommandWorker = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.join.worker"
	CacheKeyKubeadmBootstrapToken    = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.bootstraptoken"
	CacheKeyKubeadmCACertHashes      = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.discovery.cacertsha256"
	CacheKeyKubeadmCertificateKey    = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.certificatekey"
	CacheKeyClusterCACert            = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].pki.ca.cert"
	CacheKeyClusterCAKey             = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].pki.ca.key"
	CacheKeyAdminKubeconfig          = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeconfig.admin"
	CacheKeyModuleEtcdEndpoints      = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].etcd.endpoints"
	CacheArchivePathKey              = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].package.archive.path"
	CacheExtractedDirKey             = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].package.extracted.dir"
	CacheKeyHostFactsTemplate        = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].facts.host.%s"
	CacheKubeadmInitToken            = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.init.token"
	CacheKubeadmInitCertKey          = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.init.certkey"
	CacheKubeadmInitCACertHash       = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.init.cacerthash"
	CacheKubeadmK8sCACertRenew       = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.kubernetes.cacert.renew"
	CacheKubeadmK8sLeafCertRenew     = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.kubernetes.leaftcert.renew"
	CacheKubeadmEtcdCACertRenew      = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.etcd.cacert.renew"
	CacheKubeadmEtcdLeafCertRenew    = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.etcd.leafcert.renew"
	CacheKubexmK8sCACertRenew        = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubexm.kubernetes.cacert.renew"
	CacheKubexmK8sLeafCertRenew      = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubexm.kubernetes.leaftcert.renew"
	CacheKubexmEtcdCACertRenew       = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubexm.etcd.cacert.renew"
	CacheKubexmEtcdLeafCertRenew    = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubexm.etcd.leafcert.renew"
	CacheKubeconfigsIsBackup         = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeconfigs.backup"
	CacheKubeconfigsBackupPath       = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeconfigs.backup.path"
	CacheKubeCertsIsBackup           = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubecerts.backup"
	CacheKubeCertsBackupPath         = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubecerts.backup.path"
	CacheEtcdCertsIsBackup           = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].etcdcerts.backup"
	CacheEtcdCertsBackupPath         = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].etcdcerts.backup.path"
	CacheKeyEtcdLocalBackupPath      = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].etcd.local.backup.path.%s"
	CacheKeyRemoteBackupPath         = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].k8s.remote.backup.path.%s"
	CacheKeyKubeadmBackupPath        = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.upgrade.backup.path.%s"
	CacheKeyTargetVersion            = "kubexm.run[%s].pipeline[%s].module[%s].task[%s].kubeadm.upgrade.target.version"
)
