package v1alpha1

import (
	"fmt"
	"strings"
	"github.com/mensylisir/kubexm/pkg/util" // Import the util package
	"github.com/mensylisir/kubexm/pkg/util/validation"
)

// StorageConfig defines the storage configurations for the cluster.
type StorageConfig struct {
	OpenEBS             *OpenEBSConfig `json:"openebs,omitempty" yaml:"openebs,omitempty"`
	DefaultStorageClass *string        `json:"defaultStorageClass,omitempty" yaml:"defaultStorageClass,omitempty"`
}

// OpenEBSConfig defines settings for OpenEBS storage provisioner.
type OpenEBSConfig struct {
	BasePath string                 `json:"basePath,omitempty" yaml:"basePath,omitempty"`
	Enabled  *bool                  `json:"enabled,omitempty" yaml:"enabled,omitempty"`
	Version  *string                `json:"version,omitempty" yaml:"version,omitempty"`
	Engines  *OpenEBSEngineConfig `json:"engines,omitempty" yaml:"engines,omitempty"`
}

// OpenEBSEngineConfig allows specifying configurations for different OpenEBS storage engines.
type OpenEBSEngineConfig struct {
	Mayastor      *OpenEBSEngineMayastorConfig      `json:"mayastor,omitempty" yaml:"mayastor,omitempty"`
	Jiva          *OpenEBSEngineJivaConfig          `json:"jiva,omitempty" yaml:"jiva,omitempty"`
	CStor         *OpenEBSEnginecStorConfig         `json:"cstor,omitempty" yaml:"cstor,omitempty"`
	LocalHostPath *OpenEBSEngineLocalHostPathConfig `json:"localHostPath,omitempty" yaml:"localHostPath,omitempty"`
}

// OpenEBSEngineMayastorConfig holds Mayastor specific settings.
type OpenEBSEngineMayastorConfig struct {
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty"`
}

// OpenEBSEngineJivaConfig holds Jiva specific settings.
type OpenEBSEngineJivaConfig struct {
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty"`
}

// OpenEBSEnginecStorConfig holds cStor specific settings.
type OpenEBSEnginecStorConfig struct {
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty"`
}

// OpenEBSEngineLocalHostPathConfig holds LocalHostPath specific settings.
type OpenEBSEngineLocalHostPathConfig struct {
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenEBSEngineConfig) DeepCopyInto(out *OpenEBSEngineConfig) {
	*out = *in
	if in.Mayastor != nil {
		in, out := &in.Mayastor, &out.Mayastor
		*out = new(OpenEBSEngineMayastorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Jiva != nil {
		in, out := &in.Jiva, &out.Jiva
		*out = new(OpenEBSEngineJivaConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CStor != nil {
		in, out := &in.CStor, &out.CStor
		*out = new(OpenEBSEnginecStorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalHostPath != nil {
		in, out := &in.LocalHostPath, &out.LocalHostPath
		*out = new(OpenEBSEngineLocalHostPathConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenEBSEngineConfig.
func (in *OpenEBSEngineConfig) DeepCopy() *OpenEBSEngineConfig {
	if in == nil {
		return nil
	}
	out := new(OpenEBSEngineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenEBSEngineMayastorConfig) DeepCopyInto(out *OpenEBSEngineMayastorConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = *in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenEBSEngineMayastorConfig.
func (in *OpenEBSEngineMayastorConfig) DeepCopy() *OpenEBSEngineMayastorConfig {
	if in == nil {
		return nil
	}
	out := new(OpenEBSEngineMayastorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenEBSEngineJivaConfig) DeepCopyInto(out *OpenEBSEngineJivaConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = *in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenEBSEngineJivaConfig.
func (in *OpenEBSEngineJivaConfig) DeepCopy() *OpenEBSEngineJivaConfig {
	if in == nil {
		return nil
	}
	out := new(OpenEBSEngineJivaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenEBSEnginecStorConfig) DeepCopyInto(out *OpenEBSEnginecStorConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = *in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenEBSEnginecStorConfig.
func (in *OpenEBSEnginecStorConfig) DeepCopy() *OpenEBSEnginecStorConfig {
	if in == nil {
		return nil
	}
	out := new(OpenEBSEnginecStorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenEBSEngineLocalHostPathConfig) DeepCopyInto(out *OpenEBSEngineLocalHostPathConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = *in
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenEBSConfig) DeepCopyInto(out *OpenEBSConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = *in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = *in
	}
	if in.Engines != nil {
		in, out := &in.Engines, &out.Engines
		*out = new(OpenEBSEngineConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenEBSConfig.
func (in *OpenEBSConfig) DeepCopy() *OpenEBSConfig {
	if in == nil {
		return nil
	}
	out := new(OpenEBSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenEBSEngineLocalHostPathConfig.
func (in *OpenEBSEngineLocalHostPathConfig) DeepCopy() *OpenEBSEngineLocalHostPathConfig {
	if in == nil {
		return nil
	}
	out := new(OpenEBSEngineLocalHostPathConfig)
	in.DeepCopyInto(out)
	return out
}

// SetDefaults_StorageConfig sets default values for StorageConfig.
func SetDefaults_StorageConfig(cfg *StorageConfig) {
	if cfg == nil {
		return
	}
	if cfg.OpenEBS != nil {
		SetDefaults_OpenEBSConfig(cfg.OpenEBS)
	}
}

// SetDefaults_OpenEBSConfig sets default values for OpenEBSConfig.
func SetDefaults_OpenEBSConfig(cfg *OpenEBSConfig) {
	if cfg == nil {
		return
	}
	if cfg.Enabled == nil {
		cfg.Enabled = util.BoolPtr(true)
	}

	if cfg.Enabled != nil && *cfg.Enabled {
		if cfg.BasePath == "" {
			cfg.BasePath = "/var/openebs/local"
		}
		if cfg.Engines == nil {
			cfg.Engines = &OpenEBSEngineConfig{}
		}
		if cfg.Engines.LocalHostPath == nil {
			cfg.Engines.LocalHostPath = &OpenEBSEngineLocalHostPathConfig{}
		}
		if cfg.Engines.LocalHostPath.Enabled == nil {
			cfg.Engines.LocalHostPath.Enabled = util.BoolPtr(true)
		}
		if cfg.Engines.Mayastor == nil {
			cfg.Engines.Mayastor = &OpenEBSEngineMayastorConfig{Enabled: util.BoolPtr(false)}
		}
		if cfg.Engines.Jiva == nil {
			cfg.Engines.Jiva = &OpenEBSEngineJivaConfig{Enabled: util.BoolPtr(false)}
		}
		if cfg.Engines.CStor == nil {
			cfg.Engines.CStor = &OpenEBSEnginecStorConfig{Enabled: util.BoolPtr(false)}
		}
	} else {
		if cfg.Engines != nil {
			if cfg.Engines.LocalHostPath != nil {
				cfg.Engines.LocalHostPath.Enabled = util.BoolPtr(false)
			}
			if cfg.Engines.Mayastor != nil {
				cfg.Engines.Mayastor.Enabled = util.BoolPtr(false)
			}
			if cfg.Engines.Jiva != nil {
				cfg.Engines.Jiva.Enabled = util.BoolPtr(false)
			}
			if cfg.Engines.CStor != nil {
				cfg.Engines.CStor.Enabled = util.BoolPtr(false)
			}
		}
	}
}

// Validate_StorageConfig validates StorageConfig.
func Validate_StorageConfig(cfg *StorageConfig, verrs *validation.ValidationErrors, pathPrefix string) {
	if cfg == nil {
		return
	}
	if cfg.OpenEBS != nil {
		Validate_OpenEBSConfig(cfg.OpenEBS, verrs, pathPrefix+".openebs")
	}
	if cfg.DefaultStorageClass != nil && strings.TrimSpace(*cfg.DefaultStorageClass) == "" {
		verrs.Add(pathPrefix+".defaultStorageClass", "cannot be empty if specified")
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.OpenEBS != nil {
		in, out := &in.OpenEBS, &out.OpenEBS
		*out = new(OpenEBSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultStorageClass != nil {
		in, out := &in.DefaultStorageClass, &out.DefaultStorageClass
		*out = new(string)
		**out = *in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// Validate_OpenEBSConfig validates OpenEBSConfig.
func Validate_OpenEBSConfig(cfg *OpenEBSConfig, verrs *validation.ValidationErrors, pathPrefix string) {
	if cfg == nil {
		return
	}
	if cfg.Enabled != nil && *cfg.Enabled {
		if strings.TrimSpace(cfg.BasePath) == "" {
			verrs.Add(pathPrefix+".basePath", "cannot be empty if OpenEBS is enabled")
		}

		if cfg.Version != nil {
			if strings.TrimSpace(*cfg.Version) == "" {
				verrs.Add(pathPrefix+".version", "cannot be only whitespace if specified")
			} else if !util.IsValidRuntimeVersion(*cfg.Version) {
				verrs.Add(pathPrefix+".version", fmt.Sprintf("'%s' is not a recognized version format", *cfg.Version))
			}
		}
	}
}
