// +build !ignore_autogenerated

package v1alpha1

// This file contains placeholder validation functions to satisfy calls from Validate_Cluster.
// These should be replaced with actual validation logic for types not having their own validation yet.

// Validate_RoleGroupsSpec is a placeholder.
func Validate_RoleGroupsSpec(cfg *RoleGroupsSpec, verrs *ValidationErrors, pathPrefix string) {
	// TODO: Implement actual validation for RoleGroupsSpec if not defined elsewhere
	if cfg == nil && verrs != nil {
		// verrs.Add("%s: roleGroups section cannot be nil if present in spec", pathPrefix)
	}
}

// Validate_ControlPlaneEndpointSpec is a placeholder.
func Validate_ControlPlaneEndpointSpec(cfg *ControlPlaneEndpointSpec, verrs *ValidationErrors, pathPrefix string) {
	// TODO: Implement actual validation for ControlPlaneEndpointSpec if not defined elsewhere
	if cfg == nil && verrs != nil {
		// verrs.Add("%s: controlPlaneEndpoint section cannot be nil if present in spec", pathPrefix)
	}
	if cfg != nil && cfg.Port != 0 && (cfg.Port <= 0 || cfg.Port > 65535) {
         verrs.Add("%s.port: invalid port number %d", pathPrefix, cfg.Port)
    }
}

// Validate_SystemSpec is a placeholder.
func Validate_SystemSpec(cfg *SystemSpec, verrs *ValidationErrors, pathPrefix string) {
	// TODO: Implement actual validation for SystemSpec if not defined elsewhere
	if cfg == nil && verrs != nil {
		// verrs.Add("%s: system section cannot be nil if present in spec", pathPrefix)
	}
}

// Removed placeholders for functions that are expected to be in their respective type files:
// Validate_ContainerRuntimeConfig
// Validate_ContainerdConfig
// Validate_EtcdConfig
// Validate_KubernetesConfig
// Validate_PreflightConfig
// Validate_KernelConfig
// Validate_AddonConfig
// Validate_StorageConfig
// Validate_RegistryConfig
// Validate_OSConfig

// KeepalivedConfig, HAProxyConfig, NginxLBConfig, KubeVIPConfig might also need placeholders
// if their validation functions are called from ha_types.go validation AND not defined with their types.
// For now, assuming these might be defined in ha_types.go or dedicated files.
// If they are still reported as missing, they can be added back here as placeholders.

// Removed Validate_KeepalivedConfig (defined in keepalived_types.go)
// Removed Validate_HAProxyConfig (defined in haproxy_types.go)
// Removed Validate_NginxLBConfig (defined in nginx_lb_types.go)
// Removed Validate_KubeVIPConfig (defined in kubevip_types.go)
